[book]
authors = ["David Paul Graham", "Scott Christian"]
language = "en"
multilingual = false
src = "src"
title = "e-Manifest Developer Docs"
description = "Documentation for developer looking to use the RCRAInfo/e-Manifest web services"

[output.html]
git-repository-url = "https://github.com/USEPA/e-manifest"
edit-url-template = "https://github.com/USEPA/e-manifest/edit/master/docs/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = true
level = 2