name: Test NPM package

on:
  pull_request:
    paths:
      - 'emanifest-js/**'


jobs:
  release:
    name: Test NPM package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './emanifest-js'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
