name: Test e-Manifest Python Package

on:
  push:
    paths:
      - e-manifest-py/*

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e-manifest-py
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Test with pytest
        run: |
          pytest